### PR TITLE
Challenge1/44mura

### PR DESCRIPTION
**Pull request by nyoshimura**

### CODE REVIEW

**Comment by nyoshimura** [comment]
I did challenge 1 and 2.
Summary of those are described in challenge1.html and challenge2.html.

**Comment by thedimlebowski** [comment]
Dear  Nyoshimura,

Thank you for the pull requests.

First of all:
- Can you please create a folder with your github username in analysis folders?

General comments:
- You showed that you can code in Python.
- Your graphs were of good quality with labels and legend.
- You showed some knowledge in machine learning including clustering and regression.

Challenge 1 comments:
- Linear regression has been used.
- Shows that you know the basics of regression
- A more advanced machine learning technique could have been used

Challenge 2 comments:
- Nice plots of the time-series.
- Good insight for the missing data even though counting the number of points for each day seems more straightforward than your resampling method.
- Good use of k-means (even though I find k-means overkill for a 1d clustering problem)

My personal opinion of your work is positive, and I consider your passed both challenges (provided you merge you two pull requests in one and create folders in each analysis folders). Congratulations!

Thanks again for taking the time to address these challenges, we'll be in touch as soon as possible.

Cheers,
Dimitry - CEDL Data Scientist.

**Comment by JustGlowing** [comment]
Hi Nyoshimura,

Thank for your contribution to our challenge!

Here are some general comments about your submissions:
- You seem familiar with the core libraries for data analysis (scipy, pandas, matplotlib and statsmodels).
- Your code seems clear and, most of the time, well commented.

About challenge 1:
- Your solution is straightforward and appropriate for the problem.
- From the comments and the way you derived the features, it seems that you could be proficient in time series analysis.
- A description of the model you developed would have been appreciated. 

About challenge 2:
- The charts that you proposed are very nice and show that you have good visualization skill.
- The results of the clustering analysis are good, but a more detailed comment about it would have been better.

My response about your submission is also positive. Congratulations again!

Giuseppe - CEDL Data Scientist

**Comment by nyoshimura** [comment]
Dear Mr. Dimitry and Mr. Giuseppe,

Thank you for your reviews and positive responses.

I created folders with my github username in analysis folders, so please check my submission.
And if there is any problem, please notify me.

Sincerely,
Nobuto Yoshimura

**Comment by shirakia** [comment]
Hi, it seems that your submission is not pushed to github.

**Comment by shirakia** [comment]
I fixed and merged it.

**Comment by yoheikiguchi** [comment]
Thank you, Dimitry and Giuseppe for reviewing, and of course, thank you Nyoshimura for showing a commitment to our challenge. Since this is an intern position, we agreed to go further. Further steps will be navigated via email.

**Pull request merged**
