### PR TITLE
Challenge 4 by Sakuma

### PR DESCRIPTION
**Pull request by sakuma**
Hi.
I've solved the "Challenge 4"

Please check this.
https://energy-charge.herokuapp.com/

### CODE REVIEW

**Comment by shirakia** [comment]
Thanks for nice PR!
However a test doesn't pass. Can you fix it?

**Comment by shirakia** [comment]
$ bundle exec rspec

  1) Charges GET /charge html format works!
     Failure/Error: expect(response.body).to be_include "Please access JSON request"
       expected `"<!DOCTYPE html>\n<html>\n<head>\n  <title>EnergyChargeCalculator</title>\n  <link rel=\"stylesheet\" media=\"all\" href=\"/assets/application.css\" />\n  <script src=\"/assets/application.js\"></script>\n  \n</head>\n<body>\n\n<h1>Error</h1>\n\n<p>Please access POST request</p>\n\n<h2>URL</h2>\n\n<pre class=\"request-info\">\n  <strong>POST</strong>  http://localhost:3000/charge\n</pre>\n\n<h2>Request Header</h2>\n\n<pre class=\"request-info\">\n  Accept: application/json\n  Content-Type: application/json\n</pre>\n\n<h2>Request Body</h2>\n\n※ sample\n<pre  class=\"request-info\">\n[\n  [ 0.2, 0.3, 0.2, ... ], # 24 values for 1st day, 1 am, 2 am .. 12 am, 1 pm ..  12 pm\n  [ 0.2, 0.3, 0.2, ... ], # 24 values for 2nd day\n  ...\n  [ 0.2, 0.3, 0.2, ... ]  # 24 values for 31st day\n]\n</pre>\n\n\n\n</body>\n</html>\n".include?("Please access JSON request")` to return true, got false
     # ./spec/requests/charges_spec.rb:10:in `block (4 levels) in <top (required)>'

 48/48 |============================================================================================== 100 ==============================================================================================>| Time: 00:00:00 

Finished in 0.45787 seconds (files took 2.15 seconds to load)
48 examples, 1 failure

Failed examples:

rspec ./spec/requests/charges_spec.rb:9 # Charges GET /charge html format works!

**Comment by shirakia** [comment]
I use ruby 2.2.2. Or please note your Ruby version

**Comment by sakuma** [comment]
@shirakia 

Oh, Sorry...
I fixed spec file.   

https://github.com/sakuma/EnergyDataSimulationChallenge/commit/e446c535773d7e1b45b2d544c38f87eb49c783df

**Comment by cuzic** [comment]
Good job !
I have also reviewed your work.

**Pull request merged**
