### PR TITLE
Challenge2/soma11soma

### PR DESCRIPTION
**Pull request by soma11soma11**
Thank you for taking the time to appraise my work!! I look forward to our forthcoming Skype interview!!

### CODE REVIEW

**Comment by thedimlebowski** [comment]
Hi soma11soma11,

Thanks a lot for you PR. We have checked it and it looks promising. However, on their own the figures are not very informative. Could you maybe comment them and let us know what you think of the data?
Can you derive any insight from them? any structure? missing fields?...

Cheers,
Dimitry

**Comment by soma11soma11** [comment]
Hi Dimitry! 
I added README.md.
I also fixed 3.clusters.py.

Cheers!!
Soma

**Comment by thedimlebowski** [comment]
Thanks for the changes, it's easier to understand now.
- You showed a good technical knowledge of Python including advanced libraries such as sklearn and pandas.
- Your plots are readable (at the exception of the 3d plot!).
- The analysis you made based on your figures is logical and your conclusions are for most of them correct.
- I'm skeptical about the clustering in the consumption/time space.
  We will get back to you ASAP.

Thanks again,
Dimitry

**Comment by thedimlebowski** [comment]
We will keep you posted very quickly about the position!

**Comment by soma11soma11** [comment]
Sorry for my late reply. I am in Malaysia and did not have Wifi connection.
I added 3.clusters_fix.py, which I think works properly.

Cheers!!
Soma

**Comment by nyoshimura** [comment]
Thanks a lot for you PR. I checked your PR. 
- I think the fixed clustering works properly in the consumption space (3.clusters_fix.jpg).
- The conclusion in README.md is good explanation.

And follows are just advice.
- If you write unit in axis (ex. consumption (W)), your figure will be better to understand.
- When you show your code for other people, all import should be written at the top of a code, and write comment to separate your code into each parts (clustering part, plotting part, ...).

Cheers,
Nobuto

**Comment by soma11soma11** [comment]
I submitted challenge1!

Cheers!!
Soma

**Comment by nyoshimura** [comment]
Thank you for your PR. I checked both challenge 1 and fixed challenge 2.

About challenge 1
- You used VAR model for prediction. The step to choose this algorithm is well discussed and summarised in the notebook.
- You acquired the smoothed curves (energy production, daylight, and temperature) by using high-pass filter, but after that you calculated log-difference and first difference. Please derive P-value of the smoothed curves for comparison and explain how to decide the bandwidth.
- Please explain more detail about autocorrelations. I can't understand what you want to say here.

About challenge 2
- All previous codes are well summarised.
- Please write all import at the top of your code.

Cheers,
Nobuto

**Comment by soma11soma11** [comment]
・I deleted an autocorrelations part, as I found that I did not have to consider about autocorrelations.
Autocorrelations are used to decide lag order, but I already decided lag order by calculating AIC (and also BIC and FPE)

・I added explanation about Hodrick–Prescott filter and Augumented Dickey-Fuller test.

・I also tidied up my code, comment and conclusion.

**Pull request merged**
