### PR TITLE
add challenge3/kenkaton

### PR DESCRIPTION
**Pull request by kenkaton**
# App URL

https://powerful-shelf-97386.herokuapp.com/

# comment

It's kenkaton's challenge3.

You can check each commit from [here](https://github.com/kenkaton/MyEnergyDataSimulationChallenge/commits/master).

よろしくお願いします！

### CODE REVIEW

**Comment by shirakia** [comment]
@kenkaton Thanks for creating your PR.
Can you put all codes instead of adding it as a submodule?

**Comment by kenkaton** [comment]
@shirakia oh... I made a mistake.
I committed my code as a submodule.
Please let me know if you have any trouble.

**Comment by kenkaton** [comment]
I put my code without using submodule.

**Comment by shirakia** [comment]
@kenkaton Thanks! Now it's fine.

**Pull request merged**
